### ISSUE TITLE
Add nano support

### ISSUE THREAD

**Issue by davejamesmiller** [davejamesmiller/dotfiles#8]
For @lopeax.
- [ ] Option to change the 'e' command to use nano not vim
- [ ] Make it the default editor for Git, etc.
- [ ] Any additional configuration?

**Comment by lopeax** [comment]
To avoid conflicts, how about having n instead of needing to do an option for e? (and maybe having it updated on some places because on jericho it has syntax highlighting but in others it doesn't)

**Comment by davejamesmiller** [comment]
Could do - but wouldn't it be better if nano was the default editor so it was used for git, etc. too?

**Comment by lopeax** [comment]
Does make more sense, that's true
